# 测试配置文件 - 简化版本用于快速测试

checkpoint_path: ""  # 不使用预训练权重进行测试

# 数据配置
data:
  dataset_path: "D:/Dataset/emg2pose_dataset_mini"
  batch_size: 4
  num_workers: 0  # 测试时不使用多进程
  padding: [0, 0]
  window_length: 1000  # 更小的窗口用于测试
  val_test_window_length: 1000

# 模型配置
model:
  type: "RealtimePoseModel"
  num_position_steps: 50  # 更小的步数用于测试
  provide_initial_pos: false
  state_condition: true
  
  # 编码器配置（简化）
  encoder:
    type: "TdsNetwork"
    conv_blocks:
      - in_channels: 16
        kernel_size: 5
        out_channels: 32
        stride: 2
    tds_stages:
      - channels: 4
        feature_width: 8
        in_channels: 32
        in_conv_kernel_width: 5
        in_conv_stride: 2
        kernel_width: 3
        num_blocks: 1
        out_channels: 16
  
  # 解码器配置（简化）
  decoder:
    type: "SequentialLSTM"
    in_channels: 36  # 16 (encoder) + 20 (state)
    hidden_size: 64  # 更小的隐藏层
    num_layers: 1
    out_channels: 40  # 20 (position) + 20 (velocity)
    scale: 0.01

# 实时预测配置
realtime:
  fast_window_size: 0.5  # 更小的窗口用于测试
  correction_window_size: 1.0
  max_latency: 500
  correction_frequency: 5
  fusion_weight: 0.7
  sample_rate: 2000
  rollout_freq: 50

# 缓冲区配置（更小）
buffers:
  raw_data:
    size: 1000  # 约0.5秒@2kHz
    type: "circular"
  feature:
    size: 25   # 约0.5秒@50Hz
    type: "circular"

# 在线学习配置（禁用以简化测试）
online_learning:
  enabled: false
  learning_rates:
    encoder: 1e-6
    decoder: 1e-4
  trigger_conditions:
    error_threshold: 0.5
    data_count: 50
    time_interval: 60
    trigger_logic: "any"
  batch_size: 8
  max_grad_norm: 1.0

# 数据流模拟配置
simulation:
  packet_interval: 0.1
  packet_size:
    min: 5
    max: 20
  random_seed: 42

# 检查点配置
checkpoint:
  save_interval: 300
  save_dir: "./test_checkpoints"
  keep_last_n: 2

# 日志配置
logging:
  level: "INFO"
  tensorboard_dir: "./test_logs"
  log_interval: 5
