# 实时EMG姿态预测系统配置文件
# 基于 refer/referConfig/regression_model.yaml 严格对齐

# 数据配置
data:
  dataset_root: D:/Dataset/emg2pose_dataset_mini
  batch_size: 16
  num_workers: 2
  window_length: 10000
  val_test_window_length: 10000
  padding: [0, 0]
  skip_ik_failures: false

# 模型配置
model:
  # Encoder: TdsNetwork
  network:
    type: TdsNetwork
    conv_blocks:
      - in_channels: 16
        out_channels: 256
        kernel_size: 11
        stride: 5
      - in_channels: 256
        out_channels: 256
        kernel_size: 5
        stride: 2
    tds_stages:
      - in_channels: 256
        in_conv_kernel_width: 17
        in_conv_stride: 4
        num_blocks: 2
        channels: 16
        feature_width: 16
        kernel_width: 9
      - in_channels: 256
        in_conv_kernel_width: 9
        in_conv_stride: 2
        num_blocks: 2
        channels: 16
        feature_width: 16
        kernel_width: 5
        out_channels: 64
  
  # Decoder: SequentialLSTM
  decoder:
    type: SequentialLSTM
    in_channels: 84  # 64 (features) + 20 (state)
    out_channels: 40  # 20 (pos) + 20 (vel)
    hidden_size: 512
    num_layers: 2
    scale: 0.01
  
  # Head: VEMG2PoseWithInitialState
  type: VEMG2PoseWithInitialState
  num_position_steps: 500
  state_condition: true
  rollout_freq: 50
  provide_initial_pos: false

# 训练配置（第一阶段默认关闭）
train:
  enabled: false
  learning_rate: 0.001
  loss_weights:
    mae: 1
    fingertip_distance: 0.01
  max_epochs: 100
  early_stopping_patience: 10

# 运行时配置
runtime:
  device: cuda  # cuda/cpu
  seed: 42
  buffer:
    max_samples: 10000

# 日志配置
logging:
  log_dir: ./logs
  tensorboard:
    enabled: true
  save_predictions: false

# 在线学习配置（占位，第一阶段不实现）
online_learning:
  enabled: false
  learning_rate: 0.0001
  update_frequency: 100

# 评估配置
eval:
  alignment_check: true
  metrics:
    - angle_mae
    - angle_mse
  output_format: json

# 参考权重路径
reference_checkpoint: refer/referCheckpoint/regression_vemg2pose.ckpt

# 常量
constants:
  emg_sample_rate: 2000
  num_joints: 20
  num_emg_channels: 16

